services:
  bankapp:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
    container_name: bankapp
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_PORT: ${DB_PORT:-3306}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      OLLAMA_URL: ${OLLAMA_URL}
    restart: always
    networks:
      - bankapp-net

networks:
  bankapp-net:
    driver: bridge