version: '3.9'

networks:
  bankapp-net:

volumes:
  mysql-data:
  ollama-data:


services:

  mysql:
    image: mysql:8.0
    container_name: bank_app
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports: 
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - bankapp-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 10s
  

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      - bankapp-net
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 30s


  bank-app:
    build: .
    container_name: bankapp
    ports:
      - "80:8080"
    depends_on:
      mysql:
        condition: service_healthy
      ollama:
        condition: service_healthy
    
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      OLLAMA_URL: ${OLLAMA_URL}
    networks:
      - bankapp-net