apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.gateway.tls.certManager.issuerName }}
spec:
  acme:
    email: {{ .Values.gateway.tls.certManager.email | quote }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ .Values.gateway.tls.certManager.issuerName }}-account-key
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: {{ .Values.gateway.name }}
                kind: Gateway
