name: Main Pipeline

on:
  push:
    branches: [start]

permissions:
  contents: read
  pull-requests: write
  security-events: read

jobs:
  call-reusable-build-test:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      java-version: '21'
      runs_tests: true

  prepare:
    runs-on: ubuntu-latest
    outputs:
      image-name: ${{ steps.prep.outputs.image-name }}
      short-sha: ${{ steps.prep.outputs.short-sha }}
    steps:
      - name: Prepare image details
        id: prep
        run: |
          echo "image-name=sana2026/ai-bankapp-devops" >> $GITHUB_OUTPUT
          echo "short-sha=sha-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

    

  call-reusable-docker:
    needs: [call-reusable-build-test, prepare]
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image-name: ${{ needs.prepare.outputs.image-name }}
      image-tag: ${{ needs.prepare.outputs.short-sha }}
    secrets: inherit

  deploy:
    needs: [call-reusable-docker, prepare]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy to production
        run: |
          echo "Deploying image: ${{ needs.prepare.outputs.image-name }}:${{ needs.prepare.outputs.short-sha }} to production"


  notify: 
    needs: [call-reusable-build-test, call-reusable-docker, deploy]
    runs-on: ubuntu-latest
    if: always() # Run this job regardless of previous job outcomes
    steps:
      - name: Send Slack notification
        run: |
          STATUS="Success"
          if [ "${{ needs.deploy.result }}" != "success" ]; then
            STATUS="Failed"
          fi

          curl -X POST -H 'Content-type: application/json' --data "{
            \"text\":\"🚀 Main Pipeline\nStatus: $STATUS\nBranch: ${{ github.ref_name }}\"
          }" \
          ${{ secrets.SLACK_WEBHOOK_URL }}
