name: Main Pipeline

on:
  push:
    branches: [start]

jobs:
  call-reusable-build-test:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      java-version: '21'
      runs_tests: true

  prepare:
    runs-on: ubuntu-latest
    outputs:
      image-name: ${{ steps.prep.outputs.image-name }}
      short-sha: ${{ steps.prep.outputs.short-sha }}
    steps:
      - name: Prepare image details
        id: prep
        run: |
          echo "image-name=$sana2026/ai-bankapp-devops" >> $GITHUB_OUTPUT
          echo "short-sha=sha-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

  call-reusable-docker:
    needs: [call-reusable-build-test, prepare]
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image-name: ${{ needs.prepare.outputs.image-name }}
      image-tag: ${{ needs.prepare.outputs.short-sha }}
    secrets: inherit

  deploy:
    needs: [call-reusable-docker, prepare]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy to production
        run: |
          echo "Deploying image: ${{ needs.prepare.outputs.image-name }}:${{ needs.prepare.outputs.short-sha }} to production"
