name: Main Pipeline
on: 
  push:
    branches: [start]

jobs:
  call-reusable-build-test:
    uses: ./.github/workflows/reusable-build-test.yml
    with: 
      java-version: 21
      runs_tests: true

  call-reusable-docker-latest:
    needs: call-reusable-build-test
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image-name: ${{github.repository}}
      image-tag: latest
    secrets: inherit

  call-reusable-docker-sha:
    needs: call-reusable-build-test
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image-name: ${{github.repository}}
      image-tag: sha-${{ github.sha }}
    secrets: inherit

  deploy:
    needs: [call-reusable-build-test, call-reusable-docker-latest, call-reusable-docker-sha]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: print deployment info
        run: |
          echo "Deploying application with Docker image: ${{ needs.call-reusable-docker.outputs.image_url }}"
          echo "Test result from build and test workflow: ${{ needs.call-reusable-build-test.outputs.test-result }}"  
      
            
