name: Reusable Docker Workflow
on:
  workflow_call:
    inputs:
      image-name:
        description: 'The name of the Docker image to build'
        required: true
        type: string
      image-tag:
        description: 'The tag of the built Docker image'
        required: false
        type: string
        default: 'latest'
   
    secrets:
      
      DOCKER_USERNAME:
        description: 'DockerHub username'
        required: true
      DOCKER_TOKEN:
        description: 'DockerHub access token'
        required: true

    outputs:
      image_url:
        description: 'The URL of the built Docker image'
        value: ${{ jobs.DockerBuild.outputs.image_url }}

jobs:
  DockerBuild:
    runs-on: ubuntu-latest
    outputs:
      image_url: ${{ steps.build.outputs.image_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98


      - name: login to DockerHub
        uses: docker/login-action@4a8376e001c7725687f0624d1c3698a3f6ab337e
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        id: build
        run: |
          docker build \
            -t ${{ inputs.image-name }}:latest \
            -t ${{ inputs.image-name }}:${{ inputs.image-tag }} .


          echo "image_url=${{ inputs.image-name }}:${{ inputs.image-tag }}" >> $GITHUB_OUTPUT

          
      # 🔐 Trivy Scan Step (DevSecOps)
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          image-ref: ${{ inputs.image-name }}:${{ inputs.image-tag }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'
          exit-code: '1'

      # 📄 Upload to GitHub Security Tab
      - name: Upload Sarif Report
        uses: github/codeql-action/upload-sarif@4cbe7bef850a2b9688db7dbe6133a045b3627fcd
        with:
          sarif_file: trivy-results.sarif

      # Push Docker image to DockerHub    
      - name: Push Docker image
        run: |  
          docker push ${{ inputs.image-name }}:latest
          if [ "${{ inputs.image-tag }}" != "latest" ]; then
            docker push ${{ inputs.image-name }}:${{ inputs.image-tag }}
          fi
