name: SAST - Static Security Scan

on:
  workflow_call:

permissions:
  contents: read
  security-events: write

jobs:
  sast:
    name: SAST - Semgrep
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Semgrep SAST Scanner
        uses: semgrep/semgrep-action@v1
        with:
          config: >-
            p/java
            p/owasp-top-ten
            p/secrets
